#!/usr/bin/env python3
"""Package site videos as chunked data for the browser video player."""

import base64
import json
from pathlib import Path


ASSET_DIR = Path(__file__).resolve().parents[1] / "site" / "assets"
CHUNK_BYTES = 196_608
VIDEO_NAMES = ("overview", "exploration")


def build_video_data(name: str) -> Path:
    chunks = []
    with (ASSET_DIR / f"{name}.mp4").open("rb") as video:
        while data := video.read(CHUNK_BYTES):
            encoded = base64.b64encode(data).decode("ascii")
            # Keep video data intact during word-based text anonymization.
            chunks.append(encoded.replace("+", "_0").replace("/", "_1"))
    destination = ASSET_DIR / f"{name}-video-data.js"
    destination.write_text(
        "// Generated by scripts/build_site_video_data.py.\n"
        f"window.voxroomVideoData({json.dumps(name)}, "
        f"{json.dumps(chunks, separators=(',', ':'))});\n",
        encoding="utf-8",
        newline="\n",
    )
    return destination


def main() -> None:
    for name in VIDEO_NAMES:
        destination = build_video_data(name)
        print(f"{destination.name}: {destination.stat().st_size} bytes")


if __name__ == "__main__":
    main()
